resources:
  - pvc.yaml
  - deployment.yaml
  - service-gateway.yaml
  - service.yaml

configMapGenerator:
  - name: inference-replay-config
    literals:
      - mode=off
    options:
      disableNameSuffixHash: true
