steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "DOCKER_BUILDKIT=1"
    args:
      [
        "build",
        "-t",
        "$_IMAGE_URI",
        "-f",
        "agents/Dockerfile",
        "--target",
        "platform",
        "--build-arg",
        "HERMES_AGENT_TAG=$_HERMES_AGENT_TAG",
        ".",
      ]
images:
  - "$_IMAGE_URI"
