steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "DOCKER_BUILDKIT=1"
    args:
      - "build"
      - "-t"
      - "$_IMAGE_URI"
      - "-t"
      - "$_IMAGE_URI_LATEST"
      - "-f"
      - "deploy/docker/Dockerfile"
      - "--target"
      - "$_TARGET"
      - "--build-arg"
      - "HERMES_AGENT_TAG=$_HERMES_AGENT_TAG"
      - "."
images:
  - "$_IMAGE_URI"
  - "$_IMAGE_URI_LATEST"
substitutions:
  _IMAGE_URI: ""
  _IMAGE_URI_LATEST: ""
  _TARGET: ""
  _HERMES_AGENT_TAG: ""
