apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: agent-system
data:
  config.yaml: |
    model_list:
      - model_name: model-default
        litellm_params:
          model: chatgpt/gpt-5.4
    litellm_settings:
      callbacks: ["otel", "prometheus"]
